 /*************************************************************
 * ITM - Departamento de Ingeniería en Sistemas Computacionales
 * Semestre Agosto - Diciembre 2020
 * Projecto: BattleCity
 * Paquete: Main
 * Archivo: Puntajes
 * Descripción: Clase para el diseño de la tabla de puntajes
 *
 *************************************************************/
package Main;

import static Main.Menu.loadFont;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Graphics;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Puntajes extends javax.swing.JFrame {
    
    DefaultTableModel modeloTabla; 
    

    public Puntajes() {
        initComponents();
        modeloTabla = new DefaultTableModel();
        cargarTabla();
        titulo();
        botones();
        this.setLocationRelativeTo(null);
    }
    
    public void cargarTabla(){
        Font font = loadFont();
        modeloTabla.addColumn("nombreJugador");
        modeloTabla.addColumn("puntuacionJugador");
        miTabla.setModel(modeloTabla);    
        miTabla.setFont(font);
    }
    public void titulo(){
        Font font = loadFont();
        font = font.deriveFont(java.awt.Font.PLAIN, 20);
        jLabel1.setFont(font);
    }
    public void botones(){
        Font font = loadFont();
        font = font.deriveFont(java.awt.Font.PLAIN, 13);
        btnCargar.setFont(font);
        btnExcel.setFont(font);
        btnPDF.setFont(font);
    }
    
    
    public static Font loadFont() {
    Font font = null;
    try 
    {
        font = java.awt.Font.createFont(java.awt.Font.TRUETYPE_FONT, new File("prstart.ttf"));
        font = font.deriveFont(java.awt.Font.PLAIN, 12);
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        ge.registerFont(font);

    } catch (FontFormatException | IOException ex) 
    {
        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
    }
    return font;
    }
    
        
    

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        miTabla = new javax.swing.JTable();
        btnCargar = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        miTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(miTabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 378, 270));

        btnCargar.setFont(new java.awt.Font("Swis721 Cn BT", 1, 18)); // NOI18N
        btnCargar.setForeground(new java.awt.Color(0, 0, 204));
        btnCargar.setText("Cargar");
        btnCargar.setBorder(null);
        btnCargar.setBorderPainted(false);
        btnCargar.setContentAreaFilled(false);
        btnCargar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 130, 30));

        btnPDF.setBackground(new java.awt.Color(153, 153, 153));
        btnPDF.setFont(new java.awt.Font("Swis721 Cn BT", 1, 18)); // NOI18N
        btnPDF.setForeground(new java.awt.Color(0, 0, 204));
        btnPDF.setText("Generar PDF");
        btnPDF.setBorder(null);
        btnPDF.setContentAreaFilled(false);
        btnPDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });
        getContentPane().add(btnPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 170, 30));

        btnExcel.setFont(new java.awt.Font("Swis721 Cn BT", 1, 18)); // NOI18N
        btnExcel.setForeground(new java.awt.Color(0, 0, 204));
        btnExcel.setText("Generar Excel");
        btnExcel.setBorder(null);
        btnExcel.setContentAreaFilled(false);
        btnExcel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 230, 30));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOpaque(true);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 56, 460, -1));

        jLabel1.setFont(new java.awt.Font("Swis721 Cn BT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Puntajes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 170, 50));

        Fondo.setBackground(new java.awt.Color(0, 0, 0));
        Fondo.setOpaque(true);
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
      Conectar c = new Conectar();
        Connection CON = c.conectarMYSQL();
        PreparedStatement ps = null;
        ResultSet rs = null;

        try {
            String query = "select nombreJugador,puntuacionJugador from mejores_puntajes";

            ps = CON.prepareStatement(query);
            rs = ps.executeQuery();

            //mientras sigan existiendo registros en la BD
            while (rs.next()) {

                //debemos recorre nuestra base de datos
                Object[] filas = new Object[2];

                for (int i = 0; i < filas.length; i++) {
                    filas[i] = rs.getObject(i + 1);  //obtenemos los registros fila por fila
                }

                //añadimos los registros a nuesra tabla
                
                modeloTabla.addRow(filas);
                
            }

        } catch (SQLException e) {
            System.err.println("Error");
            e.printStackTrace(System.out);
        }

    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
      GenerarExcel excel = new GenerarExcel(); 
      Icon icono = new ImageIcon(getClass().getResource("/img/excel.png"));
      JOptionPane.showMessageDialog(null, "EXCEL CREADO", "", JOptionPane.PLAIN_MESSAGE,icono);
      
      excel.crearExcel(); 
     
    }//GEN-LAST:event_btnExcelActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
      GenerarPDF  pdf = new GenerarPDF(); 
      Icon icono = new ImageIcon(getClass().getResource("/img/pdf.png"));
      JOptionPane.showMessageDialog(null, "PDF CREADO", "", JOptionPane.PLAIN_MESSAGE,icono);
      
      pdf.crearPDF(); 
      
    }//GEN-LAST:event_btnPDFActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Puntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Puntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Puntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Puntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Puntajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnPDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable miTabla;
    // End of variables declaration//GEN-END:variables
}
